#Install epel-release
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install epel-release
      yum: name=epel-release state=latest
      ignore_errors: yes
    - name: ensure firewall is at the latest version
      yum: name=firewalld state=latest
